### PR TITLE
Fix background color issue in newsletter

### PR DESCRIPTION
**Pull request by eliasfang**
### Administrative Info
Monday Board ID: 940408300
Make sure your branch name conforms to: `<feature/staging/hotfix/...>/[username]/[Monday Item ID]-[3-4 word description separated by dashes]`. Otherwise, please rename your branch and create a new PR.

### Changes
What changes did you make?
- Copied and pasted contents of newsletter.html to header.html for testing
- Wrapped all contents of the body inside a table
- Styled table with background color and background image
- Attempted dark mode issue by adding meta tags and media query in the head (still an issue for both Gmail and Apple Mail)

### Testing
How did you confirm your changes worked? 
- Sent test emails through Gmail
- Viewed on desktop Gmail, mobile Gmail, and mobile Apple Mail

### Confirmation of Change 
Upload a screenshot, if possible. Otherwise, please provide instructions on how to see the change.

| [Desktop Gmail] | [Mobile Gmail] | [Mobile Apple Mail] | Mobile Dark Mode |
| --- | --- | --- | --- |
| newsletter_desktop_gmail_screenshot | newsletter_phone_gmail_screenshot | newsletter_phone_applemail_screenshot | newsletter_darkmode_phone_gmail_screenshot |

### CODE REVIEW

**Review by wes-chen — COMMENTED** [review]
Can I see what the behavior is in dark mode? Do you have a screenshot

**Comment by wes-chen** [comment]
It also seems like this is just the background color, not the background image with the lightbulbs. Is this intentional? @eliasfang

**Review by wes-chen — APPROVED** [review]
I'm going to approve this for now, but I'm also going to make a new task regarding this dark mode issue and assign it to you. The newsletter will not ship without this issue being resolved.

**Review by shravan1k — APPROVED** [review]
LGTM

**Pull request merged**
