### PR TITLE
reorg files + add python boilerplate

### PR DESCRIPTION
**Pull request by wes-chen**
### Administrative Info
Monday Board ID: 940408300
Make sure your branch name conforms to: `<feature/staging/hotfix/...>/[username]/[Monday Item ID]-[3-4 word description separated by dashes]`. Otherwise, please rename your branch and create a new PR.

### Changes
What changes did you make?
- moved `.html` files into an html folder
- created a `py` folder with boilerplate for python html generation
- created corresponding python files for outline.

### Testing
How did you confirm your changes worked? 
- new files are created
- run `python newsletter.py`
- a file named `newsletter.html` will be generated

### Confirmation of Change 
Upload a screenshot, if possible. Otherwise, please provide instructions on how to see the change.

newsletter.html contents:
```
<!DOCTYPE html>
<html>
  <head>
    <title>TSE Newsletter</title>
    <link href="newsletter.css" rel="stylesheet">
  </head>
  <body>
    <table>
      <tbody>
        <tr>
          <td>
            <h1>This is the header.</h1>
            <h2>This is the greetings.</h2>
            <p>This is the body with a left line.</p>
            <p>This is the body with a right line.</p>
            <p>This is the body with a no line.</p>
            <h1>This is the footer.</h1>
          </td>
        </tr>
      </tbody>
    </table>
  </body>
</html>
```

### CODE REVIEW

**Review by eliasfang — COMMENTED** [review]
Would the newsletter.html file be overwritten every time the python script is run?

**Comment by wes-chen** [comment]
good point @eliasfang , we can add on later to prepend the date of the newsletter onto the filename. Right now it overwrites `newsletter.html` every time.

**Review by eliasfang — APPROVED** [review]
That sounds good to me.

**Review by shravan1k — APPROVED** [review]
Looks good!

**Pull request merged**
